"use client";
import React, { useEffect, useState } from "react";
import style from "./page.module.scss"

// export const metadata = {
//   title: 'Movie API SITE',
//   description: 'Generated by create next app',
// }


const Movie = () => {
  const [movies, setMovies] = useState([]);
  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://api.themoviedb.org/3/movie/popular?api_key=697729d3f274ce88cf5729d38280fd33"
      );      if (!res.ok) {
        throw new Error("Failed to fetch data");
      }
      const data = await res.json();
      setMovies(data.results);
    };
    getData();
  }, []);
  console.log(movies);
  
  return <div className={style}>Movie</div>;
};
export default Movie;